### Load data and libraries and learn about the data

kaggle resource: https://www.kaggle.com/sharmajayesh76/iris-data-train-test-split

In [14]:
from sklearn import datasets # importing sklearn datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
import numpy as np
from sklearn.metrics import accuracy_score

iris = datasets.load_iris() # Loading the iris dataset and calling it iris
#dat = pd.read_csv(r'C:\Users\Saffra\Documents\KH\mock_ppg_data.csv')

#print(iris) # This prints more than just the data
print(type(iris))
len(iris.data)
len(iris.target)

#iris.head()  
# =============================================================================
# Note: head() doesn't work because "sklearn always works internally with numpy 
# and returns numpy arrays. There is no head function for a numpy array"
#https://stackoverflow.com/questions/41416320/attributeerror-head-not-found-when-printing-head-in-python
# =============================================================================

print(iris.data) # This just prints the data
print(iris.target) # Prints the "target" or the numeric value of the iris name
print(iris.target_names) # Prints the actual names

<class 'sklearn.utils.Bunch'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 

### Split the data

In [2]:
# These are the attributes we could print out:
for keys in iris.keys() :
    print(keys)

# Assigning X and y values to be the data and the target (flower type)
X=iris.data
y=iris.target

X_Train, X_Test, y_Train, y_Test = train_test_split(X, y, test_size = 0.3, random_state = 0) # Random state = seed
len(X_Train)
len(X_Test)
len(y_Train)
len(y_Test)
print ("X_train: ", X_Train)
print ("y_train: ", y_Train)
print("X_test: ", X_Test)
print ("y_test: ", y_Test)


data
target
target_names
DESCR
feature_names
filename
X_train:  [[5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [6.5 3.  5.8 2.2]
 [6.4 2.8 5.6 2.1]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [6.5 3.2 5.1 2. ]
 [6.7 3.3 5.7 2.1]
 [4.5 2.3 1.3 0.3]
 [6.2 3.4 5.4 2.3]
 [4.9 3.  1.4 0.2]
 [5.7

### Train a Gaussian NB model

In [3]:
# GaussianNB assumes that each feature is entirely independent of one another.
classifier = GaussianNB() # classifier is just a variable name so it could be changed to anything
classifier.fit(X_Train, y_Train)
classifier.score(X_Test, y_Test)

1.0

### Make predictions

In [4]:
targets_predicted = classifier.predict(X_Test)
print(targets_predicted)
# How can I compare predicted targets to the actual targets and output the resulting accuracy?


[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0]


### 5. IMPLEMENT YOUR OWN NEW "ALGORITHM"

In [12]:
##DecisionTreeClassifier
#https://towardsdatascience.com/how-to-build-a-gender-classifier-in-python-using-scikit-learn-13c7bb502f2e

classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_Train, y_Train) #fill in x and y with training data
classifier_predict = classifier.predict(X_Test)
classifier_predict


array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

### Test the accuracy of your classifier

In [18]:
classifier_accuracy = accuracy_score(classifier_predict, y_Test)
classifier_accuracy
print(f"The classifier has {classifier_accuracy}% accuracy.")

The classifier has 0.9777777777777777% accuracy
